spring:
  application:
    name: "configserver"  # Name of the application
  profiles:
    active: native        # Using the native profile for configuration
    cloud:                # This is incorrectly nested under profiles
      config:
        server:
        native:
          search-locations: "file:///Users//emreozcan//Documents//config" # Path to the config files
server:
  port: 8071              # Server will run on port 8071
